In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [5]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [6]:
Y = tf.placeholder(tf.float32)

In [7]:
w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [8]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [9]:
# const function => 차이를 평균 내준다.
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
"""
    cost를 최소화 한다!
    텐서플로우가 알아서 최소 cost를 가지는 W와 b를 조정한다.
    이 부분은 텐서플로우 라이브러리가 알아서 해주는 magic이라 생각하자.
    
    learning_rate는 충분히 작은 값을 준다.
"""
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# launch the graph in a session
sess = tf.Session()

In [12]:
# initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [13]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if(step%10 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  38.09974 
Prediction:
 [148.03964 193.88765 182.40845 203.2656  148.102  ]
10 Cost:  19.057537 
Prediction:
 [144.20273 189.24734 177.85124 198.30016 144.55782]
20 Cost:  18.977888 
Prediction:
 [144.20622 189.22304 177.84222 198.28755 144.53447]
30 Cost:  18.898811 
Prediction:
 [144.2213  189.2127  177.84692 198.28992 144.5218 ]
40 Cost:  18.82011 
Prediction:
 [144.23642 189.20248 177.8517  198.29236 144.50926]
50 Cost:  18.741886 
Prediction:
 [144.25143 189.19225 177.85641 198.29474 144.49669]
60 Cost:  18.664064 
Prediction:
 [144.26648 189.18211 177.86119 198.29718 144.48422]
70 Cost:  18.586674 
Prediction:
 [144.2814  189.1719  177.86586 198.29953 144.47173]
80 Cost:  18.509647 
Prediction:
 [144.29636 189.1618  177.87059 198.30194 144.4593 ]
90 Cost:  18.433016 
Prediction:
 [144.31125 189.1517  177.8753  198.30432 144.4469 ]
100 Cost:  18.356833 
Prediction:
 [144.3261  189.14162 177.87997 198.3067  144.43454]
110 Cost:  18.280964 
Prediction:
 [144.3409  189.13153 

970 Cost:  13.049158 
Prediction:
 [145.47963 188.35968 178.24469 198.48283 143.4824 ]
980 Cost:  13.001074 
Prediction:
 [145.49144 188.3517  178.24846 198.48457 143.4728 ]
990 Cost:  12.953311 
Prediction:
 [145.50319 188.34375 178.25218 198.48627 143.4632 ]
1000 Cost:  12.905739 
Prediction:
 [145.51492 188.33582 178.2559  198.48796 143.45361]
1010 Cost:  12.858417 
Prediction:
 [145.52663 188.3279  178.25963 198.48965 143.44408]
1020 Cost:  12.811394 
Prediction:
 [145.53825 188.31998 178.2633  198.4913  143.43452]
1030 Cost:  12.76456 
Prediction:
 [145.54993 188.31213 178.26704 198.49303 143.42506]
1040 Cost:  12.71796 
Prediction:
 [145.56151 188.30423 178.27068 198.49466 143.41556]
1050 Cost:  12.671623 
Prediction:
 [145.57312 188.29645 178.2744  198.49635 143.40616]
1060 Cost:  12.6255455 
Prediction:
 [145.58464 188.28862 178.27805 198.49799 143.39671]
1070 Cost:  12.579667 
Prediction:
 [145.59618 188.28082 178.28171 198.49966 143.38734]
1080 Cost:  12.534061 
Prediction:
 

1920 Cost:  9.432146 
Prediction:
 [146.47304 187.68816 178.56116 198.61806 142.68025]
1930 Cost:  9.402649 
Prediction:
 [146.48225 187.68195 178.56412 198.61922 142.67293]
1940 Cost:  9.3733225 
Prediction:
 [146.49141 187.67572 178.56703 198.62033 142.6656 ]
1950 Cost:  9.344164 
Prediction:
 [146.50058 187.66956 178.56998 198.6215  142.65834]
1960 Cost:  9.315119 
Prediction:
 [146.50974 187.66342 178.57292 198.62265 142.6511 ]
1970 Cost:  9.286225 
Prediction:
 [146.51883 187.65723 178.5758  198.62378 142.64381]
1980 Cost:  9.257509 
Prediction:
 [146.52792 187.65112 178.57874 198.62492 142.6366 ]
1990 Cost:  9.22888 
Prediction:
 [146.537   187.645   178.58165 198.62605 142.6294 ]
2000 Cost:  9.200444 
Prediction:
 [146.54602 187.63889 178.58453 198.62715 142.62221]
