In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# make training data with matrix
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]

y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
"""
    shape을 정하는 부분을 보자.
    가장 안쪽의 데이터 개수는 X의 경우 3, Y의 경우 1로 정해진다.
    
    그 다음 []의 데이터 개수는 인스턴스 개수로, 이는 정해지지 않은 n개이다.
"""
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
"""
    W는 행렬의 형태로 표시하게 되면, 3행 1열의 모양을 띄므로
"""
W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [6]:
# 가정을 행렬곱으로 표현한다!
hypothesis = tf.matmul(X, W) + b

In [7]:
# const function => 차이를 평균 내준다.
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# launch the graph in a session
sess = tf.Session()

In [10]:
# initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_data, Y: y_data})
    
    if(step%10 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  12665.374 
Prediction:
 [[256.7581 ]
 [300.9058 ]
 [300.55325]
 [325.653  ]
 [229.03719]]
10 Cost:  13.501721 
Prediction:
 [[157.24156]
 [181.32115]
 [182.71051]
 [197.32689]
 [137.82948]]
20 Cost:  13.314577 
Prediction:
 [[156.92636]
 [180.96902]
 [182.34964]
 [196.93561]
 [137.56616]]
30 Cost:  13.243629 
Prediction:
 [[156.91132]
 [180.9776 ]
 [182.34422]
 [196.93137]
 [137.57794]]
40 Cost:  13.173099 
Prediction:
 [[156.89725]
 [180.98726]
 [182.3399 ]
 [196.92833]
 [137.59053]]
50 Cost:  13.102918 
Prediction:
 [[156.88318]
 [180.99686]
 [182.33557]
 [196.92528]
 [137.60307]]
60 Cost:  13.033139 
Prediction:
 [[156.86917]
 [181.00645]
 [182.33127]
 [196.92226]
 [137.61559]]
70 Cost:  12.963697 
Prediction:
 [[156.8552 ]
 [181.01602]
 [182.32698]
 [196.91924]
 [137.62808]]
80 Cost:  12.8946705 
Prediction:
 [[156.84126]
 [181.02557]
 [182.3227 ]
 [196.91623]
 [137.64052]]
90 Cost:  12.826007 
Prediction:
 [[156.82736]
 [181.03508]
 [182.31842]
 [196.91324]
 [137.65294]]


 [138.50418]]
860 Cost:  8.514723 
Prediction:
 [[155.86256]
 [181.6958 ]
 [182.0219 ]
 [196.7056 ]
 [138.51424]]
870 Cost:  8.469754 
Prediction:
 [[155.85133]
 [181.7035 ]
 [182.01842]
 [196.70319]
 [138.52428]]
880 Cost:  8.424982 
Prediction:
 [[155.8401 ]
 [181.7112 ]
 [182.01498]
 [196.70076]
 [138.5343 ]]
890 Cost:  8.380468 
Prediction:
 [[155.82889]
 [181.71884]
 [182.01154]
 [196.69835]
 [138.54428]]
900 Cost:  8.336181 
Prediction:
 [[155.81772]
 [181.7265 ]
 [182.00812]
 [196.69597]
 [138.55424]]
910 Cost:  8.292164 
Prediction:
 [[155.8066 ]
 [181.73412]
 [182.00468]
 [196.69356]
 [138.56418]]
920 Cost:  8.248395 
Prediction:
 [[155.7955 ]
 [181.74173]
 [182.00128]
 [196.69121]
 [138.57408]]
930 Cost:  8.204801 
Prediction:
 [[155.78441]
 [181.74931]
 [181.99786]
 [196.68881]
 [138.58395]]
940 Cost:  8.161463 
Prediction:
 [[155.77338]
 [181.75688]
 [181.99446]
 [196.68646]
 [138.59383]]
950 Cost:  8.118427 
Prediction:
 [[155.76236]
 [181.76442]
 [181.99109]
 [196.6841 ]


1730 Cost:  5.3846474 
Prediction:
 [[154.98862]
 [182.29416]
 [181.7531 ]
 [196.51877]
 [139.29309]]
1740 Cost:  5.356559 
Prediction:
 [[154.97972]
 [182.30025]
 [181.75037]
 [196.51686]
 [139.30103]]
1750 Cost:  5.3286505 
Prediction:
 [[154.97084]
 [182.30632]
 [181.74765]
 [196.515  ]
 [139.30891]]
1760 Cost:  5.300843 
Prediction:
 [[154.96199]
 [182.31238]
 [181.7449 ]
 [196.5131 ]
 [139.3168 ]]
1770 Cost:  5.2732 
Prediction:
 [[154.95314]
 [182.31842]
 [181.74219]
 [196.51123]
 [139.32465]]
1780 Cost:  5.2457304 
Prediction:
 [[154.94435]
 [182.32445]
 [181.73949]
 [196.50935]
 [139.33249]]
1790 Cost:  5.2183685 
Prediction:
 [[154.93556]
 [182.33047]
 [181.73679]
 [196.50748]
 [139.3403 ]]
1800 Cost:  5.1911864 
Prediction:
 [[154.92682]
 [182.33647]
 [181.73409]
 [196.50562]
 [139.3481 ]]
1810 Cost:  5.1641626 
Prediction:
 [[154.91809]
 [182.34244]
 [181.73138]
 [196.50377]
 [139.35587]]
1820 Cost:  5.137257 
Prediction:
 [[154.90936]
 [182.3484 ]
 [181.72873]
 [196.5019 ]
