In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [12]:
"""
    Training Data를 정의한다.
    바이너리 데이터가 아닌, A, B, C의 결과를 가진다.(3개의 클래스를 가진다)
"""
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [13]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3  # class의 갯수

In [14]:
"""
    W의 경우 4개의 x 데이터가 들어와서 3개의 클래스 결과로 출력된다.
"""
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [15]:
"""
    tf.nn.softmax는 softmax 알고리즘을 동작시킨다.
"""
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [16]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [21]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if(step%200==0):
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    
    all = sess.run(hypothesis, feed_dict={X: x_data})
    print(all, sess.run(tf.arg_max(all, 1)))

0 3.8147779
200 0.53892994
400 0.41989756
600 0.32144538
800 0.24714556
1000 0.22231346
1200 0.20218188
1400 0.18533072
1600 0.17100807
1800 0.15868539
2000 0.14797354
[[2.0189291e-06 8.1933680e-04 9.9917859e-01]
 [2.3440863e-03 8.0585256e-02 9.1707069e-01]
 [5.0084331e-08 1.5684895e-01 8.4315103e-01]
 [1.9773915e-06 8.5537291e-01 1.4462514e-01]
 [2.4063337e-01 7.4762601e-01 1.1740677e-02]
 [1.2610213e-01 8.7389344e-01 4.3291211e-06]
 [7.6575434e-01 2.3423132e-01 1.4314900e-05]
 [9.2586589e-01 7.4133821e-02 2.0030508e-07]] [2 2 2 1 1 1 0 0]
